- name: Execute Gradle Build
  shell:
    cmd: ./gradlew build
    chdir: /home/vagrant/MinimumViableDataspace

- name: Execute Gradle Dockerize with Persistence
  shell:
    cmd: ./gradlew -Ppersistence=true dockerize
    chdir: /home/vagrant/MinimumViableDataspace

- name: Start MinimumViableDataspace for Consumer
  shell:
    cmd: docker compose up -d
    chdir: /home/vagrant/MinimumViableDataspace/deployment/docker/consumer
  when: "'consumer' in group_names"

- name: Start MinimumViableDataspace for Provider
  shell:
    cmd: docker compose up -d
    chdir: /home/vagrant/MinimumViableDataspace/deployment/docker/provider
  when: "'provider' in group_names"
