- name: Execute Gradle Build
  shell:
    cmd: ./gradlew build
    chdir: /home/vagrant/MinimumViableDataspace

- name: Execute Gradle Dockerize with Persistence
  shell:
    cmd: ./gradlew -Ppersistence=true dockerize
    chdir: /home/vagrant/MinimumViableDataspace

- name: Start MinimumViableDataspace for Consumer
  shell:
    cmd: docker compose up -d
    chdir: /home/vagrant/MinimumViableDataspace/deployment/docker/consumer
  when: "'consumer' in group_names"

- name: Ensure seed-consumer-vm.sh is executable
  file:
    path: /home/vagrant/MinimumViableDataspace/seed-consumer-vm.sh
    mode: '0755'
  when: "'consumer' in group_names"

- name: Ensure Unix Line Endings for seed-consumer-vm.sh
  shell:
    cmd: dos2unix seed-consumer-vm.sh
    chdir: /home/vagrant/MinimumViableDataspace
  when: "'consumer' in group_names"

- name: Start MinimumViableDataspace for Provider
  shell:
    cmd: docker compose up -d
    chdir: /home/vagrant/MinimumViableDataspace/deployment/docker/provider
  when: "'provider' in group_names"

- name: Ensure seed-provider-vm.sh is executable
  file:
    path: /home/vagrant/MinimumViableDataspace/seed-provider-vm.sh
    mode: '0755'
  when: "'provider' in group_names"

- name: Ensure Unix Line Endings for seed-provider-vm.sh
  shell:
    cmd: dos2unix seed-provider-vm.sh
    chdir: /home/vagrant/MinimumViableDataspace
  when: "'provider' in group_names"