- name: Install dependencies for docker
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: latest

- name: Detect current ubuntu version
  shell: lsb_release -cs
  register: ubuntu_version

- name: Detect current cpu architecture
  shell: dpkg --print-architecture
  register: cpu_architecture

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: "deb [arch={{ cpu_architecture.stdout }}] https://download.docker.com/linux/ubuntu {{ ubuntu_version.stdout }} stable"
    filename: "docker.list"
    state: present

- name: Install Docker CE
  apt:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
    update_cache: yes

- name: Probe Docker daemon
  service:
    name: docker
    state: started
    enabled: yes

- name: Create Docker group
  group:
    name: docker
    state: present

- name: Add user permissions for docker
  shell: "usermod -aG docker vagrant"