Vagrant.configure("2") do |config|
  vm_box = "ubuntu/jammy64"
  vm_box_version = "20241002.0.0"
  vm_cpus = 2
  vm_ram = 4096

  # TODO: Cleanup mapped ports
  # Consumer VM
  config.vm.define "mvd-consumer-vm" do |consumer|
    consumer.vm.box = vm_box
    consumer.vm.box_version = vm_box_version
    consumer.vm.hostname = "mvd-consumer-vm"
    consumer.vm.network "private_network", ip: "192.168.1.101"

    # Ports
    # PostgreSQL Port
    consumer.vm.network "forwarded_port", guest: 5432, host: 5432, auto_correct: true
    # Vault Port
    consumer.vm.network "forwarded_port", guest: 8200, host: 8200, auto_correct: true
    # Controlplane Management Port
    consumer.vm.network "forwarded_port", guest: 8081, host: 8081, auto_correct: true
    # IdentityHub Presentation Port
    consumer.vm.network "forwarded_port", guest: 7082, host: 7082, auto_correct: true
    # IdentityHub DID Port
    consumer.vm.network "forwarded_port", guest: 7083, host: 7083, auto_correct: true
    # Connector Catalog Port
    consumer.vm.network "forwarded_port", guest: 8084, host: 8084, auto_correct: true

    consumer.vm.synced_folder "../", "/tmp/MinimumViableDataspace"
    consumer.vm.provider "virtualbox" do |vb|
      vb.name = "MVD-Consumer-VM"
      vb.memory = vm_ram
      vb.cpus = vm_cpus
    end
    consumer.vm.provision "shell", inline: <<-SHELL
        cp -r /tmp/MinimumViableDataspace /home/vagrant/MinimumViableDataspace
        chown -R vagrant:vagrant /home/vagrant/MinimumViableDataspace
    SHELL
  end

  # Provider VM
  config.vm.define "mvd-provider-vm" do |provider|
    provider.vm.box = vm_box
    provider.vm.box_version = vm_box_version
    provider.vm.hostname = "mvd-provider-vm"
    provider.vm.network "private_network", ip: "192.168.1.102"

    # Ports
    # PostgreSQL Port
    provider.vm.network "forwarded_port", guest: 5432, host: 5433, auto_correct: true
    # Vault Port
    provider.vm.network "forwarded_port", guest: 8200, host: 8300, auto_correct: true
    # Catalog Protocol Port
    provider.vm.network "forwarded_port", guest: 9082, host: 9082, auto_correct: true
    # QNA Connector Protocol Port
    provider.vm.network "forwarded_port", guest: 4082, host: 4082, auto_correct: true
    # Dataplane Public Port
    provider.vm.network "forwarded_port", guest: 11002, host: 11002, auto_correct: true

    provider.vm.synced_folder "../", "/tmp/MinimumViableDataspace"
    provider.vm.provider "virtualbox" do |vb|
      vb.name = "MVD-Provider-VM"
      vb.memory = vm_ram
      vb.cpus = vm_cpus
    end
    provider.vm.provision "shell", inline: <<-SHELL
        cp -r /tmp/MinimumViableDataspace /home/vagrant/MinimumViableDataspace
        chown -R vagrant:vagrant /home/vagrant/MinimumViableDataspace
    SHELL
  end

  # Issuer VM
  config.vm.define "mvd-issuer-vm" do |issuer|
    issuer.vm.box = vm_box
    issuer.vm.box_version = vm_box_version
    issuer.vm.hostname = "mvd-issuer-vm"
    issuer.vm.network "private_network", ip: "192.168.1.253"
    # Jaeger Web UI Port
    issuer.vm.network "forwarded_port", guest: 16686, host: 16686, auto_correct: true
    issuer.vm.synced_folder "../", "/tmp/MinimumViableDataspace"
    issuer.vm.provider "virtualbox" do |vb|
      vb.name = "MVD-Issuer-VM"
      vb.memory = vm_ram
      vb.cpus = vm_cpus
    end
    issuer.vm.provision "shell", inline: <<-SHELL
        cp -r /tmp/MinimumViableDataspace /home/vagrant/MinimumViableDataspace
        chown -R vagrant:vagrant /home/vagrant/MinimumViableDataspace
    SHELL
  end

  # Ansible Control VM
  config.vm.define "mvd-ansible-control-vm" do |ansible|
    ansible.vm.box = vm_box
    ansible.vm.box_version = vm_box_version
    ansible.vm.hostname = "mvd-ansible-control-vm"
    ansible.vm.network "private_network", ip: "192.168.1.254"
    ansible.vm.synced_folder "./ansible", "/home/vagrant/ansible"
    ansible.vm.synced_folder "./.vagrant", "/home/vagrant/.vagrant"
    ansible.vm.provider "virtualbox" do |vb|
        vb.name = "MVD-Ansible-Control-VM"
        vb.memory = 2048
        vb.cpus = 1
    end
    ansible.vm.provision "shell", inline: <<-SHELL
        sudo apt update -y
        sudo apt install -y software-properties-common
        sudo add-apt-repository --yes --update ppa:ansible/ansible
        sudo apt install -y ansible
        chmod 600 /home/vagrant/.vagrant/machines/mvd-consumer-vm/virtualbox/private_key
        chmod 600 /home/vagrant/.vagrant/machines/mvd-provider-vm/virtualbox/private_key
        cd /home/vagrant/ansible
        ansible-playbook -i inventory main.yml
    SHELL
  end
end
