services:
  consumer-postgres:
    image: postgres:16.3-alpine3.20
    container_name: consumer-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres-initdb-config.sql:/docker-entrypoint-initdb.d/postgres-initdb-config.sql
    ports:
      - "5432:5432"